# Generated by Django 3.2 on 2021-04-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomFamille', models.CharField(max_length=255, verbose_name='nom famille')),
                ('nomP', models.CharField(max_length=255, verbose_name='nom pere')),
                ('prenomP', models.CharField(max_length=255, verbose_name='prenom pere')),
                ('etatP', models.CharField(choices=[('D', 'décédé(e)'), ('V', 'vivant(e)')], max_length=200, verbose_name='état pere')),
                ('professionP', models.CharField(max_length=255, verbose_name='Profession pere')),
                ('santeP', models.CharField(max_length=200, null=True, verbose_name='sante Pere')),
                ('revenuP', models.FloatField(default=0.0, verbose_name='revenu Pere')),
                ('nomM', models.CharField(max_length=255, verbose_name='nom Mère')),
                ('prenomM', models.CharField(max_length=255, verbose_name='prenom Mère')),
                ('etatM', models.CharField(choices=[('D', 'décédé(e)'), ('V', 'vivant(e)')], max_length=200, verbose_name='état Mère')),
                ('professionM', models.CharField(max_length=255, verbose_name='Profession Mère')),
                ('santeM', models.CharField(max_length=200, null=True, verbose_name='sante Mère')),
                ('revenuM', models.FloatField(default=0.0, verbose_name='revenu Mère')),
                ('nmbreEnfant', models.IntegerField(default=0, verbose_name='nombre enfant')),
            ],
            options={
                'verbose_name': 'famille',
                'ordering': ['revenuP'],
            },
        ),
    ]
