# Generated by Django 3.2 on 2021-04-18 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.famille')),
            ],
        ),
    ]
